### ISSUE TITLE
ServiceNotFoundException

### ISSUE THREAD

**Issue by jpintor14** [PaymentSuite/PaypalWebCheckoutBundle#28]
I'm trying to install the Bundle, but a ServiceNotFoundException appears in my Symfony Bundle (src\Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass line 58 ).

```
The service "paypal_web_checkout.manager" has a dependency on a non-existent service "payment.event.dispatcher"
```

Any idea? I'm using Symfony v.2.6.3

Thanks for your time.

**Comment by mmoreram** [comment]
Hi @jpintor14 

Let's take a look! :D Thanks for your reporting! ^^

ping @mickaelandrieu @alch

**Comment by mickaelandrieu** [comment]
Hi @jpintor14,

can you check the PaymentCoreBundle is in your vendors and if the service "payment.event.dispatcher" is in your container ?

(https://github.com/PaymentSuite/PaymentCoreBundle/blob/master/Resources/config/services.yml)

You can call this command:

```bash
php app/console container:debug payment.event.dispatcher
```

I'm not sure, but you probably need to add the PaymentCoreBundle to the list of bundles in ``app/AppKernel.php`` file.

**Comment by jpintor14** [comment]
Yes, CoreBundle is in vendor directory, so I added it in AppKernel, but the cmd also display me the error:

![image](https://cloud.githubusercontent.com/assets/10533447/7395424/0faacf02-ee9a-11e4-84d1-995cf0129a0e.png)

**Comment by arkaitzgarro** [comment]
You must implement a PaymentBridgeBundle containing a PaymentBridge Service to make it work. Check de docs for more information: 

http://payment-suite.readthedocs.org/en/latest/configuration.html#paymentbridge-service

**Comment by jpintor14** [comment]
Ok, here's my problem, I had to add in services.yml::

```
payment.bridge:
        class: YourProjectName\PaymentBridgeBundle\Services\PaymentBridge
```

Now I'm going to test the Bundle!


Thanks alot for your advice.

**Comment by mmoreram** [comment]
:+1:
